name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: ${{ matrix.os }}.${{ matrix.compiler.name }}.${{ matrix.build_type }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        build_type: [ Debug, Release ]
        compiler:
          - { name: GNU, CC: gcc, CXX: g++ }
          - { name: LLVM, CC: clang, CXX: clang++ }

    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake
        run: |
          cmake -B ${{ github.workspace }}/build \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -DUORB_BUILD_TESTS=ON \
            -DUORB_BUILD_EXAMPLES=ON \
            -DCMAKE_C_COMPILER=${{ matrix.compiler.CC }} \
            -DCMAKE_CXX_COMPILER=${{ matrix.compiler.CXX }}

      - name: Build
        run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.build_type }} --parallel

      - name: Test
        working-directory: ${{ github.workspace }}/build
        run: ctest -C ${{ matrix.build_type }} --output-on-failure

  sanitizer:
    name: ubuntu-latest.${{ matrix.sanitizer.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sanitizer:
          - name: asan-ubsan
            flags: -fsanitize=address,undefined -fno-omit-frame-pointer
          - name: tsan
            flags: -fsanitize=thread -fno-omit-frame-pointer

    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake
        run: |
          cmake -B ${{ github.workspace }}/build \
            -DCMAKE_BUILD_TYPE=Debug \
            -DUORB_BUILD_TESTS=ON \
            -DUORB_BUILD_EXAMPLES=ON \
            -DCMAKE_C_COMPILER=clang \
            -DCMAKE_CXX_COMPILER=clang++ \
            -DCMAKE_C_FLAGS="${{ matrix.sanitizer.flags }}" \
            -DCMAKE_CXX_FLAGS="${{ matrix.sanitizer.flags }}" \
            -DCMAKE_EXE_LINKER_FLAGS="${{ matrix.sanitizer.flags }}"

      - name: Build
        run: cmake --build ${{ github.workspace }}/build --config Debug --parallel

      - name: Test
        working-directory: ${{ github.workspace }}/build
        run: ctest -C Debug --output-on-failure
        env:
          ASAN_OPTIONS: detect_leaks=1:halt_on_error=1
          UBSAN_OPTIONS: halt_on_error=1
          TSAN_OPTIONS: halt_on_error=1
